name: flutter_map
description: A Dart implementation of Leaflet for Flutter apps
version: 0.11.0
repository: https://github.com/johnpryan/flutter_map
module:
  androidX: true
  
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^1.10.15

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0-nullsafety.0
  latlong: 
    git:
      url: https://github.com/p-shapovalov/dart-latlong.git  
      ref: 42bdf38862fc5e4ded2c1fcb9c7d2579858270d1
  async: ^2.5.0
  vector_math: ^2.1.0
  proj4dart:  
    git:
      url: https://github.com/p-shapovalov/proj4dart.git  
      ref: e687ef23508ea9e356a25f895e6bc0fb989254cd
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  location: ^4.1.0
  flutter_test:
    sdk: flutter
  test: ^1.16.5
