name: flutter_map
description: A Dart implementation of Leaflet for Flutter apps
version: 0.11.0
repository: https://github.com/johnpryan/flutter_map
module:
  androidX: true
  
environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ^1.10.15

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0-nullsafety.0
  latlong: 
    git:
      url: https://github.com/p-shapovalov/dart-latlong.git  
      ref: 8891ea32e73df4a0cf2eec74ec0707149cb1ec7e
  async: ^2.5.0
  vector_math: ^2.1.0
  proj4dart:  
    git:
      url: https://github.com/p-shapovalov/proj4dart.git  
      ref: 404fef3c543d1d84ee90a18e6546d8c1e92f09cc
  meta: ^1.3.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
  location: ^4.1.0
  flutter_test:
    sdk: flutter
  test: ^1.16.5
